--
-- PostgreSQL database dump
--

--
-- Name: books; Type: TABLE; Owner: postgres
--

CREATE TABLE books (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    bookname text NOT NULL,
    bookcategory text NOT NULL,
    reserved integer NOT NULL DEFAULT (0),
    borrowed integer NOT NULL DEFAULT (0),
    available integer GENERATED ALWAYS AS (CASE WHEN [Reserved] = 0 and [Borrowed] = 0 THEN 1 ELSE 0 END) STORED,
    dateadded timestamp with time zone NOT NULL,
    CONSTRAINT "PK_books" PRIMARY KEY (id)
);




-- ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: expenses; Type: TABLE DATA; Owner: postgres
--

COPY public.books (bookname, bookcategory) FROM stdin;
FireFlies   Fiction
StarShip    Fiction
Cosmology   Astron
Evolution   Science
\.

--
-- PostgreSQL database dump complete
--
